signaturebot:
  arm_controller:
      #publish all joint states -----------------------------------
      state:
        type: joint_state_controller/JointStateController
        publish_rate: 50 #Hz
      #position Controllers ---------------------------------------
      effort:
        pitch_joint:
          type: effort_controllers/JointEffortController
          joint: pitch
          pid: {p: 5.0, i: 20.0, i_clamp: 100}
        yaw_joint:
          type: effort_controllers/JointEffortController
          joint: yaw
          pid: {p: 5.0, i: 20.0, i_clamp: 100}
        extension_joint:
          type: effort_controllers/JointEffortController
          joint: extension
          pid: {p: 5.0, i: 20.0, i_clamp: 100}
