signaturebot:
      #publish all joint states -----------------------------------
      state:
        type: joint_state_controller/JointStateController
        publish_rate: 50 #Hz
      #position Controllers ---------------------------------------
      trajectory:
        type: "effort_controllers/JointTrajectoryController"
        joints:
          - pitch
          - yaw
          - extension

        constraints:
          goal_time: 0.5
          stopped_velocity_tolerance: 0.0001
          pitch:
            trajectory: 0.005
            goal: 0.002
          yaw:
            trajectory: 0.005
            goal: 0.002
          extension:
            trajectory: 0.005
            goal: 0.002

        gains:
          pitch: {p: 25.0, i: 1.0, d: 0.002, i_clamp: 1.0}
          yaw: {p: 25.0, i: 1.0, d: 0.002, i_clamp: 1.0}
          extension: {p: 4000.0, i: 10.0, d: 0.2, i_clamp: 1.0}

        velocity_ff:
          pitch: 1.0
          yaw: 1.0
          extension: 2.0

        state_publish_rate:  25
        action_monitor_rate: 30
        stop_trajectory_duration: 0
        allow_partial_joints_goal: true
