signaturebot:
      #publish all joint states -----------------------------------
      state:
        type: joint_state_controller/JointStateController
        publish_rate: 50 #Hz
      #position Controllers ---------------------------------------
      trajectory:
        type: "effort_controllers/JointTrajectoryController"
        joints:
          - joint_p_1
          - joint_y_1
          - joint_s_1

        constraints:
          goal_time: 0.5
          stopped_velocity_tolerance: 0.001
          joint_p_1:
            trajectory: 0.05
            goal: 0.02
          joint_y_1:
            trajectory: 0.05
            goal: 0.02
          joint_s_1:
            trajectory: 0.05
            goal: 0.02

        gains:
          joint_p_1: {p: 25.0, i: 1.0, d: 0.002, i_clamp: 1}
          joint_y_1: {p: 25.0, i: 1.0, d: 0.002, i_clamp: 1}
          joint_s_1: {p: 4000.0, i: 10.0, d: 0.2, i_clamp: 1}

        state_publish_rate:  25
        action_monitor_rate: 30
        stop_trajectory_duration: 0
        allow_partial_joints_goal: true
