signaturebot:
  arm_controller:
      #publish all joint states -----------------------------------
      state:
        type: joint_state_controller/JointStateController
        publish_rate: 50 #Hz
      #position Controllers ---------------------------------------
      velocity:
        pitch_joint:
          type: effort_controllers/JointVelocityController
          joint: pitch
          pid: {p: 10.0, i: 0.1, d: 0.02}
        yaw_joint:
          type: effort_controllers/JointVelocityController
          joint: yaw
          pid: {p: 10.0, i: 0.1, d: 0.02}
        extension_joint:
          type: effort_controllers/JointVelocityController
          joint: extension
          pid: {p: 100.0, i: 0.1, d: 0.2}
