# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: signature_group
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_p_1
    - joint_y_1
    - joint_s_1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
signature_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_p_1
    - joint_y_1
    - joint_s_1
  gains:
    joint_p_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_y_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_s_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1